---

organization_slug: telescoop
project_slug: my-project
main_user: my-project
main_user_uid: 1040  # must be unique for each project on the server
public_hostnames:
  - app.{{ project_slug }}.com
  - "{{ project_slug }}.{{ organization_slug }}.fr"
django_project_name: "{{ project_slug.replace('-', '_') }}_back"
backend_repo: git@gitlab.com:{{ organization_slug }}/{{ project_slug }}/backend.git
frontend_repo:
  git@gitlab.com:{{ organization_slug }}/{{ project_slug }}/{{ project_slug }}_front.git
backend_application_port: 8064  # must be unique for each project on the server
backend_static_path: /{{ organization_slug }}/{{ project_slug}}/backend_static
identity_file_path: /home/{{ main_user }}/.ssh/id_ed25519
var_log_path: /var/log/{{ organization_slug }}/{{ project_slug }}
